#!/usr/bin/env python3
"""Verify that docs/entries.json keeps up with the pages it is generated from.

`entries.json` is generated by tools/generate_site_metadata.py and consumed by
the browser: `/tonight`, `/quiz`, `/refs`, `/fortune`, `/since` and `/ascii`
read it and nothing else. So a stale copy does not fail loudly — it answers
confidently with last month's facts. A post added without re-running the
generator is invisible to `/since`, absent from `/refs`, and unguessable in
`/quiz`, while every page on the site links to it normally.

This re-derives the structure from the sources and compares. Deliberately
structural only:

  1. One entry per file in docs/posts/, and no entry for a file that is gone.
  2. Tags match the index pages, which are the only place tags exist.
  3. The link graph matches the posts' own sibling links, and no edge points
     at an entry that does not exist.
  4. Archive items match archive.html and their image files are on disk.

Dates are **not** compared. A post's lastmod is stamped the day the generator
first sees it, so a PR authored on one day and built on the next would differ
for a reason that is not drift. Checks 1-4 are date-free and deterministic.

Exit code 0 if everything is consistent, 1 otherwise. Pure stdlib, no deps.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))

# The generator owns the extraction rules; importing them is what makes this a
# comparison against the sources rather than a second, drifting parser.
from generate_site_metadata import (  # noqa: E402
    DOCS,
    index_tags,
    post_links,
    read,
)

ENTRIES = DOCS / "entries.json"


def posts_on_disk() -> set[str]:
    return {
        f"posts/{path.name}"
        for path in (DOCS / "posts").glob("*.html")
        if not path.name.startswith("_")
    }


def main() -> int:
    if not ENTRIES.exists():
        print("FAILED: docs/entries.json is missing — run tools/generate_site_metadata.py")
        return 1

    try:
        data = json.loads(read(ENTRIES))
    except json.JSONDecodeError as exc:
        print(f"FAILED: docs/entries.json is not valid JSON: {exc}")
        return 1

    errors: list[str] = []
    entries = data.get("entries", [])
    by_slug = {entry["slug"]: entry for entry in entries}

    # 1. Coverage.
    listed = {"posts/" + entry["slug"] + ".html" for entry in entries}
    on_disk = posts_on_disk()
    for rel in sorted(on_disk - listed):
        errors.append(f"{rel} has no entry")
    for rel in sorted(listed - on_disk):
        errors.append(f"entry for {rel}, which is not on disk")
    if data.get("count") != len(entries):
        errors.append(f"count says {data.get('count')} but there are {len(entries)} entries")

    # 2. Tags, against the index pages.
    tags = index_tags()
    for entry in entries:
        expected = tags.get("posts/" + entry["slug"] + ".html", [])
        if entry.get("tags", []) != expected:
            errors.append(
                f"{entry['slug']}: tags {entry.get('tags')} but the index says {expected}"
            )

    # 3. The link graph, against the posts themselves.
    for entry in entries:
        rel = "posts/" + entry["slug"] + ".html"
        if rel not in on_disk:
            continue
        expected = post_links(rel, read(DOCS / rel), on_disk)
        if entry.get("links", []) != expected:
            errors.append(f"{entry['slug']}: links {entry.get('links')} but the post links {expected}")
        for slug in entry.get("links", []):
            if slug not in by_slug:
                errors.append(f"{entry['slug']}: links to {slug}, which has no entry")

    # 4. Archive items, against archive.html and the image files.
    archive = data.get("archive", [])
    if data.get("archive_count") != len(archive):
        errors.append(
            f"archive_count says {data.get('archive_count')} but there are {len(archive)} items"
        )
    archive_html = read(DOCS / "archive.html")
    for shot in archive:
        if f'id="item-{shot["id"]}"' not in archive_html:
            errors.append(f"archive {shot['id']} is not in archive.html")
        if not (DOCS / shot["src"]).is_file():
            errors.append(f"archive {shot['id']}: missing image {shot['src']}")

    if errors:
        print("entries.json check FAILED:")
        for err in sorted(set(errors)):
            print(f"  - {err}")
        print("\nRe-run: python3 tools/generate_site_metadata.py")
        return 1

    print(
        f"OK: entries.json covers {len(entries)} posts, "
        f"{sum(len(e['links']) for e in entries)} links, {len(archive)} archive items"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
