#!/usr/bin/env bash
# Generates Posts-Reference.md for the mcamner-journal GitHub Wiki.
# Run from anywhere: ./tools/generate-wiki-posts-ref.sh
# Output: ~/mcamner-journal.wiki/Posts-Reference.md

set -euo pipefail

BASE_DIR="${MCAMNER_JOURNAL_HOME:-$HOME/mcamner-journal}"
WIKI_DIR="$HOME/mcamner-journal.wiki"
OUTPUT="$WIKI_DIR/Posts-Reference.md"
POSTS_DIR="$BASE_DIR/docs/posts"

mkdir -p "$WIKI_DIR"

extract_title() {
  local file="$1"
  local title
  # Try <title> tag — strip site suffix after · or |
  title=$(grep -m1 -i '<title>' "$file" 2>/dev/null \
    | sed -E 's/.*<title>([^<]+)<\/title>.*/\1/' \
    | sed -E 's/[[:space:]]*[·|][[:space:]]*(mcamner|journal).*//' \
    | sed -E 's/[[:space:]]*[·|][[:space:]]*.*//' \
    | tr -d '"' | tr -s ' ' | sed 's/^ *//;s/ *$//' || true)
  [[ -n "$title" ]] && { printf '%s' "$title"; return; }

  # Try <h1> tag
  title=$(grep -m1 -i '<h1' "$file" 2>/dev/null \
    | sed -E 's/.*<h1[^>]*>([^<]+)<\/h1>.*/\1/' \
    | tr -d '"' | tr -s ' ' | sed 's/^ *//;s/ *$//' || true)
  [[ -n "$title" ]] && { printf '%s' "$title"; return; }

  # Fallback: filename
  basename "$file" .html | tr '-' ' '
}

extract_type() {
  local file="$1"
  # Look for eyebrow/type class or meta line
  local type
  type=$(grep -m1 -iE 'class="eyebrow"|class="meta"' "$file" 2>/dev/null \
    | sed -E 's/.*>(Journal|Film|Book|Object|Archive|Music|Series|Note)[^<]*.*/\1/I' \
    | xargs || true)
  [[ -n "$type" ]] && { printf '%s' "$type"; return; }
  printf 'Post'
}

{
  printf '# Posts Reference\n\n'
  printf '_Auto-generated by `tools/generate-wiki-posts-ref.sh` — do not edit manually._\n\n'
  printf '%s\n\n' '---'
  printf '| Post | Type | File |\n'
  printf '|---|---|---|\n'

  while IFS= read -r file; do
    name=$(basename "$file" .html)
    title=$(extract_title "$file")
    type=$(extract_type "$file")
    rel="docs/posts/${name}.html"
    printf '| %s | %s | [`%s`](../%s) |\n' "$title" "$type" "$rel" "$rel"
  done < <(find "$POSTS_DIR" -name '*.html' | sort)

  printf '\n%s\n\n' '---'
  printf '_Generated: %s — %s posts_\n' \
    "$(date '+%Y-%m-%d %H:%M')" \
    "$(find "$POSTS_DIR" -name '*.html' | wc -l | xargs)"
} > "$OUTPUT"

printf '[ok] Written: %s\n' "$OUTPUT"
wc -l < "$OUTPUT" | xargs printf '[ok] Lines: %s\n'
